### ISSUE TITLE
Ridimensionamento dei "circle"

### ISSUE THREAD

**Issue by Wabri** [TantoPer/RandomSquare-Shooting#11]
Visualizza un quadrato perchè è necessario ridimensionare l'immagine

**Comment by DanerSound** [comment]
grande! ma in questo caso a noi servono dei quadratti ! xD

**Comment by DanerSound** [comment]
dove la passi al dimensione della immagine??

**Comment by Wabri** [comment]
Se servono dei quadrati mettici dei quadrati

**Comment by Wabri** [comment]
Il terzo è quarto parametro è il size dell'immagine:
https://github.com/TantoPer/RandomSquare-Shooting/blob/d96b267d275d312839ef9c0bbdafc4d0f62f1011/RandomSquare-Shooting/src/tantoPer/RSshooting/Frame.java#L61
